### ISSUE TITLE
Feature Request: Allow constructs to be delivered via custom Serverless Plugin(s)

### ISSUE THREAD

**Issue by walmsles** [getlift/lift#104]
I love the idea of this project and would like to make use of it as a Serverless Blueprint delivery mechanism.  I am growing Serverless build teams at the moment and being able to deliver blueprints pre-packaged like this is really beneficial.

My proposal is to enable Serverless plugin hooks for the Construct Provider load so that I can use the pre-packaged constructs in Lift OR I can replace the included with my own developed Construct Provider(s) so I can control the blueprints we share OR add my own to the pre-packaged list - I feel both scerarios make sense - Add more constructs of my own or Replace the constructs altogether.

In this way, I could build my own serverless plugin to add my own production-ready constructs built to my Corporate Cloud requirements for security and Least privilege access.  

Happy to work on adding this in if you want but wanted to Create this feature request first to understand your current roadmap and whether this is a direction you are planning to head and makes sense for this project.

Happy to discuss offline too if you wanted to chat about it in more detail.

**Comment by t-richard** [comment]
Thanks for your suggestion!

Have you seen this? https://github.com/getlift/lift/pull/52

**Comment by walmsles** [comment]
Oh Yeah, this bit of the thread :-) - https://github.com/getlift/lift/pull/52#issuecomment-901724210

Do you have a roadmap for this at all and how can I assist?

**Comment by walmsles** [comment]
Closing this particular Feature Request Issue since duplicates #52.

**Comment by t-richard** [comment]
@walmsles feel free to comment on the #52 PR to express what you would need from this.

**Comment by mnapoli** [comment]
@walmsles thank you for this issue, this is EXACTLY the kind of problem we'd like to solve eventually.

> In this way, I could build my own serverless plugin to add my own production-ready constructs built to my Corporate Cloud requirements for security and Least privilege access.

Yes! We're exploring some ideas with Lift, and also eventually with the Serverless Framework to provide a solution for these use cases.  I'm taking good note of your use case, thanks again.
