### ISSUE TITLE
SQS Queue 

### ISSUE THREAD

**Issue by dmfilipenko-affinidi** [getlift/lift#112]
Hello. Is it possible to add MessageRetentionPeriod to the queue?

**Comment by eugene-kim** [comment]
> Hi @dmfilipenko-affinidi
> 
> What's the use case here ?
> 
> The current implementation of the Queue Construct forces you to have a handler attached.
> 
> This way, your messages are processed as they arrive in the queue and the default `MessageRetentionPeriod` is 4 days which should be more than enough for your handler to process it.
> 
> And if it fails several times, it will be moved to a Dead-Letter queue where it will stay for 14 days.
> 
> This seems what most people would be looking for but your use case might be different and I would love to hear about it.

@t-richard Rather than trying to account for a variety of use cases for SQS users, wouldn't it be a win-win for everyone to allow for this field to be configurable while keeping the existing defaults?
