### ISSUE TITLE
Nightly CI failing

### ISSUE THREAD

**Issue by t-richard** [getlift/lift#116]
The scheduled CI running every night has been failing for 5 days.

This is due to https://github.com/aws/constructs/pull/771/files

This library is a dependency of CDK libraries and stopped supporting NodeJS 10 hence the failing workflow.

There's 2 solutions:
1. Dropping NodeJS 10 support
2. Restrict versions of contructs to `<=3.3.156`

:one: seems the right move to me because restricting will mean we won't be able at some point to get updates from CDK until we eventually drop NodeJS 10.

Note that there's already been a discussion about NodeJS 10 support in the past which lead to it being supported, see https://github.com/getlift/lift/pull/46

**Comment by aldebout** [comment]
Shouldn't this be closed since https://github.com/getlift/lift/pull/118?

**Comment by t-richard** [comment]
You're right!

Thanks for pointing this out
