### ISSUE TITLE
[Queue] Allow FIFO queue construct to declare delivery delay

### ISSUE THREAD

**Issue by karrui** [getlift/lift#119]
Hi, (please do point me in the right direction if it's already possible)

is there a possibility of programatically setting the [delivery delay](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-delay-queues.html) in the serverless.yml declaration?

**Comment by t-richard** [comment]
> I guess I'll have to manually set the delay in the AWS console after deployment

That's far from ideal. Maybe support for delay could be considered. What do you think @mnapoli @fredericbarthelet ?
