### ISSUE TITLE
Feature Request: Add ReceiveMessageWaitTimeSeconds option to queue configuration

### ISSUE THREAD

**Issue by fabilo-au** [getlift/lift#132]
Hi team, 

I have a few low volume queues for a small client app. They're getting usage warnings due to do constant polling from lambda functions to said queues. Based on the documentation here a solution is to configure the ReceiveMessageWaitTimeSeconds for a queue to reduce the polling interval. 
https://aws.amazon.com/premiumsupport/knowledge-center/sqs-high-charges/

Thanks, 
Fabs

**Comment by t-richard** [comment]
AFAIK the Lambda service already uses long polling for SQS by default. So not sure that would have an impact.

**Comment by fabilo-au** [comment]
You're 100% correct. "When an SQS queue is configured to invoke an AWS Lambda function, the Lambda long polls the queue."

Sorry about that!

**Comment by t-richard** [comment]
@fabilo-au no problem!

To be honest, AWS docs are not always 100% clear about the configuration applied.

Even here it says "the Lambda long polls the queue", not with which configuration. Is it 10s? 20s?

But when searching and crossing different sources it seems that 20s (the maximum) is the value used by AWS Lambda for long polling.

**Comment by fabilo-au** [comment]
Agreed, so I think I've also come to realise that lambda uses 5x concurrent polls for an SQS queue? Based on Cloudwatch metrics my queues have an average of 15 "empty receives" a minute.. which works out to be 3 polls a minute x 5 concurrent polling lambdas.
I'm not sure if there's anyway around this, I may have to temporarily merge these tasks into a single queue and handle the function routing in code.

**Comment by t-richard** [comment]
Yes there are 5 concurrent pollers by default, that's what this sentence means...

> When messages are available, Lambda reads up to **5 batches** and sends them to your function. If messages are still available, Lambda increases the number of processes that are reading batches by up to 60 more instances per minute.

([source](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#events-sqs-scaling))

**Comment by fabilo-au** [comment]
Actually, before I went down this rabbit hole I should've checked that
estimated cost. 4M requests a month (estimated minimum idle polling
requests) costs about $1.6 USD a month. I was alarmed by the client's
concern around the Free Tier Usage Limit alert email. So sorry dude. But
thank you for clarifying everything, very helpful for future reference :)
