### ISSUE TITLE
Ability to define log group retention period

### ISSUE THREAD

**Issue by manisuec** [getlift/lift#147]
### Start from the Use-case

Whenever an aws lambda function is deployed; its corresponding log group created in cloud watch by default have 'Never Expire' as log retention policy. One has to manually change this value post deployment. It would be good if ability to configure this value is also provided with 7 days as default value

### Example Config

```
worker:
  logExpire: 7 days
```

**Comment by mnapoli** [comment]
Since the function is a normal serverless framework function, you can use `logRetentionInDays`:

```yaml
provider:
  logRetentionInDays: 14
```
