### ISSUE TITLE
Feature request: Add SMS queue properties for SSE

### ISSUE THREAD

**Issue by agoodno** [getlift/lift#169]
It would be nice to be able to set these 3 properties on the queue:

- KmsMasterKeyId
- KmsDataKeyReusePeriodSeconds
- SqsManagedSseEnabled

Mentioned in the [AWS CreateQueue docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html)

As a work-around, I was able to set these properties in the AWS Console using click-ops and it didn't cause problems on a subsequent re-run of the Serverless deploy.

**Comment by fredericbarthelet** [comment]
Hi @agoodno, we recently release a new version of Lift with the introduction of the `extensions` property. [Lift extensions](https://github.com/getlift/lift#extend-lift-constructs) allows developper to override specific pieces of CloudFormation generated by Lift constructs. Could you give it a try and confirm this feature covers your use case ? I'll close this issue in the meantime, feel free to open a new one in case extensions miss something for your use case. Thanks
