### ISSUE TITLE
Unit tests failed from master branch

### ISSUE THREAD

**Issue by piolet** [getlift/lift#190]
### Description

Hi all,

I tried to fork lift project to add a little contribution, but, when i get master branch locally, i run these commands :
`npm run build
npm run test`

and i obtain this result : 
`
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Test Suites: 12 failed, 12 total
Tests:       26 failed, 36 passed, 62 total
Snapshots:   2 passed, 2 total
Time:        74.44 s, estimated 87 s
Ran all test suites.
`

same with screenshot
<img width="1200" alt="Capture d’écran 2022-04-23 à 18 43 54" src="https://user-images.githubusercontent.com/2697871/164915419-127150ab-0943-4565-8268-179eeb275924.png">

Do you have an idea about this ?

### How to Reproduce

Fork lift project
Run a container with node 16 installed

from container, run these commands : 
`
npm run build
npm run test
`

### Additional Information

i run this on a docker environment
npm's version is : 8.5.0
node's version is : v16.14.2

**Comment by mnapoli** [comment]
I ran tests from master right now, with node 17, and they are passing correctly 🤔  (not using Docker here)

**Comment by piolet** [comment]
> I ran tests from master right now, with node 17, and they are passing correctly 🤔 (not using Docker here)

With node 17, npm install is blocked :/

Chelou, isn't it ?

<img width="1178" alt="Capture d’écran 2022-04-23 à 20 02 53" src="https://user-images.githubusercontent.com/2697871/164934250-058eb3d9-ada1-4810-bc21-bc9b8baaa706.png">

snif

**Comment by fredericbarthelet** [comment]
hi @piolet, could you share the Dockerfile you use to run your tests ? I assume the test fixture path is not mounted properly in your container.
Any reason in particular you run tests in a docker container :) ?

**Comment by piolet** [comment]
> hi @piolet, could you share the Dockerfile you use to run your tests ? I assume the test fixture path is not mounted properly in your container. Any reason in particular you run tests in a docker container :) ?

hi @fredericbarthelet 
this is my docker file : 
```
FROM php:8.0-apache

#############

# Install Vim & Cron
RUN apt-get update && apt-get upgrade -y && apt-get install vim -y 

# Install Node JS
RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g grunt-cli
RUN npm install -g istanbul

WORKDIR /home
EXPOSE 80
```
And my docker compose :
```
version: '3.1'
services: 
  node_js:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    volumes:
      - ./lift:/home
    restart: always

```

my folder structure is :
/
+- lift /
+ docker-compose.yml
+ node.Dockerfile

and my main reason for using a docker container is that my main project uses a version of node (the one installed on my machine, version 15). To avoid installing another version and making my environment unstable without checking the impact beforehand, I preferred to use a container (after all, that's what they do ;) )

**Comment by piolet** [comment]
Same result with node 16.14.2 on my environment directly :(
<img width="748" alt="Capture d’écran 2022-04-25 à 12 06 17" src="https://user-images.githubusercontent.com/2697871/165068223-6ad36851-e6f5-428e-afdd-c881961d4a30.png">

**Comment by tonivdv** [comment]
I've got the same issue when I wanted to run the tests for my PR https://github.com/getlift/lift/pull/179

**Comment by piolet** [comment]
with a new computer, the tests work. It's confusing, but we can close this issue
