### ISSUE TITLE
Next JS  support for the single-page construct 

### ISSUE THREAD

**Issue by carvajalluis** [getlift/lift#197]
First of all, thank you very much for this  project,

I wouldn't even consider serverless if I didn't have  this as my level of work required to set up a stack  would be 10x 

for the matter at hand, 

Nowadays it's very useful to use, as lift means to SLS, next js to react,  simply put because it saves time and effort.  I know that Vercel has their cloud and its very easy to deploy with the cli they provide but, the issue is we cannot migrate our domain hosting to their cloud,  because I share it with multiple applications in my microservice ecosystem for my 3 environments, last time I checked they didn't allow for other than hosting all the domain and sub on them. 

If possible I would like to humbly ask for Next JS 12 support with this construct 🙏
Regards!

**Comment by fredericbarthelet** [comment]
Hi @carvajalluis and thanks for your feedback, always very much appreciated to hear Lift is helping developers out there :) !

Regarding NextJS, you can have a look at https://serverless-nextjs.com/ who is dedicated to hosting such application in a serverless manner. Maybe this will fit your requirements. Let me know :)

**Comment by carvajalluis** [comment]
thanks @fredericbarthelet !!

**Comment by mnapoli** [comment]
Also I'm thinking that if you don't need SSR you can export the NextJS website to a static website: https://nextjs.org/docs/advanced-features/static-html-export

Then you can deploy that using Lift's single-page app construct.
