### ISSUE TITLE
Uploading to S3 with presigned url

### ISSUE THREAD

**Issue by AtteR** [getlift/lift#204]
### Start from the Use-case

Hello,

The storage construct does not work when uploading with S3 presigned urls, the application will give this error:

`(Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

There has been some discussion about "Uploads" construct, but it has not been implemented yet. I have not found any other way to get the uploads working with presigned URL other than adding manually CORS to the bucket.

What exactly the storage construct is used for or is it just missing the support for presigned URLs?

### Example Config

```
constructs:
    avatars:
        type: storage
        cors: true
```

Add CORS support or new upload construct:

```
constructs:
    avatars:
        type: upload
```

### Implementation Idea

Manually editing the bucket and adding this JSON to CORS fixes the issue:

`[
    {
        "AllowedHeaders": [
            "Authorization",
            "x-amz-date",
            "x-amz-content-sha256",
            "content-type"
        ],
        "AllowedMethods": [
            "PUT",
            "POST"
        ],
        "AllowedOrigins": [
            "<domain here>"
        ],
        "ExposeHeaders": [
            "ETag"
        ]
    }
]`

**Comment by kevincerro** [comment]
You can do this with storage extensions https://github.com/getlift/lift/blob/master/docs/storage.md#extensions

Related #219

**Comment by fredericbarthelet** [comment]
Thanks @kevincerro for pointing @AtteR in the extensions direction :)
@AtteR you can update to Lift's latest version and benefit from extension to configure your storage headers as requested. I'll close this issue in the meantime. Don't hesitate to open a new one if you feel like extensions is not covering your use case.
Thanks
