### ISSUE TITLE
SQS batchSize is not limited to 10 when using maxBatchingWindow

### ISSUE THREAD

**Issue by gfaramaz** [getlift/lift#208]
### Start from the Use-case

Lift version: 1.17.0

I'm writing an SQS construct for batch processing a lot a message every 3 minutes or 1000 events
```
constructs: {
    'event-queue': {
      type: 'queue',
      batchSize: 1000,
      maxBatchingWindow: 180,
      worker: {
        handler: 'src/handler.receiver',
        memorySize: 256,
        reservedConcurrency: 1,
      },
    },
  },
```
On deploy I have an error
```
Warning: Invalid configuration encountered
  at 'constructs.event-queue': unsupported number format
```
It's because batch size is limited to 10 which [isn't true anymore in AWS since end of 2020](https://aws.amazon.com/about-aws/whats-new/2020/11/aws-lambda-now-supports-batch-windows-of-up-to-5-minutes-for-functions/) when having the maxBatchingWindow option.

As a workaround I specify it manually in serverless extensions
```
resources: {
    extensions: {
      <EventSourceMappingLogicalIdFromCloudFormation>: {
        Properties: {
          BatchSize: 1000,
        },
      },
    },
}
````

**Comment by joawan** [comment]
Any chance this issue can be looked at? Would be really great to be able to easily use batch sizes bigger than 10.

**Comment by mnapoli** [comment]
@joawan this issue is open to contributions, feel free to look at it 👍

**Comment by joawan** [comment]
@mnapoli just a friendly ping, do you think it looks alright?
