### ISSUE TITLE
[server-side-website] - allow cloudfront to use s3 url when it host static assets / site

### ISSUE THREAD

**Issue by piolet** [getlift/lift#225]
Hi all,

Thanks to the extensions I can configure, I can now set a defaultRootObject for my cdn, and also allow my S3 to host static files as a site (S3 accessible via a specific url).

Unfortunately, I still can't change the origin of the CDN which always points directly to the s3.
I would like to be able to make the origin point to the static s3 site url instead.

Is this possible?

**Comment by mnapoli** [comment]
Hi, I don't understand.

Could you clarify which constructs you are using, post sample config, and explain what is happening and what you would want to happen instead?

**Comment by piolet** [comment]
Hi @mnapoli ,

Do you remember my previous use case (in this issue : #94 ) ?
I mentioned the principle that a server side website construct could also serve pages in index.html (and not in php for example).
These pages could be managed as classic assets (like css, js, or image).

I could solve this problem with the extensions, on the condition that the CDN does not point to the S3 bucket directly, but to the url of the S3 bucket (which would allow the hosting of a static site)

I think this could be easily configured with a parameter in the constructor, such as :

```
constructs:
    website:
        type: server-side-website
        useS3Url: true // by default false
        assets:
            '/css/*': public/css
            '/js/*': public/js
```

A kind of implementation could be, in createCacheBehaviors, for origin parameter : 
```
private createCacheBehaviors(bucket: Bucket): Record<string, BehaviorOptions> {
        const behaviors: Record<string, BehaviorOptions> = {};
        for (const pattern of Object.keys(this.getAssetPatterns())) {
            if (pattern === "/" || pattern === "/*") {
                throw new ServerlessError(
                    `Invalid key in 'constructs.${this.id}.assets': '/' and '/*' cannot be routed to assets because the root URL already serves the backend application running in Lambda. You must use a sub-path instead, for example '/assets/*'.`,
                    "LIFT_INVALID_CONSTRUCT_CONFIGURATION"
                );
            }
            behaviors[pattern] = {
                // Origins are where CloudFront fetches content
                origin: this.useS3Url ? new HttpOrigin(bucket.bucketWebsiteDomainName, {protocolPolicy: OriginProtocolPolicy.HTTP_ONLY} : new S3Origin(bucket),
                allowedMethods: AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
                // Use the "Managed-CachingOptimized" policy
                // See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-policies-list
                cachePolicy: CachePolicy.CACHING_OPTIMIZED,
                viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            };
        }

        return behaviors;
    }
```

**Comment by mnapoli** [comment]
OK, should we continue the discussion in #94 then? Is there any difference with #94?

**Comment by piolet** [comment]
The difference is that since my previous issue, there is the new functionality of extensions.
With the extensions, it covers, I think, 90% of my use case.

It's slightly different from issue #94 where everything is to be done, isn't it?

**Comment by mnapoli** [comment]
OK. This is still confusing to me, but since this issue is about adding the new `useS3Url` option, I can say that there are no plans to add this option right now.

Should we close this issue?

**Comment by piolet** [comment]
snif, but ok ;)
