### ISSUE TITLE
TypeScript type definition - Lift properties should be optional - Breaking change

### ISSUE THREAD

**Issue by GuiBeal** [getlift/lift#227]
### Start from the Use-case

As soon as I add Lift type definitions to my existing `serverless.ts` config file it gives me errors because all properties defined in such type are required. I believe all of these should be optional. Also, as I understand, a recent change on this type definition caused a **breaking change**.

Below is a simple example of `serverless.ts` file using Lift type definitions.
```typescript
import type { AWS } from '@serverless/typescript';
import type { Lift } from 'serverless-lift';

const serverless: AWS & Lift = {
  service: 'my-serverless-service',
  frameworkVersion: '3',
  plugins: [
    'serverless-esbuild',
    'serverless-lift',
  ],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
  },
};

module.exports = serverless;
```

This gives me the following TypeScript errors
```
Type '{ service: string; frameworkVersion: string; plugins: string[]; provider: { name: "aws"; runtime: "nodejs14.x"; }; }' is not assignable to type 'AWS & Lift'.
  Type '{ service: string; frameworkVersion: string; plugins: string[]; provider: { name: "aws"; runtime: "nodejs14.x"; }; }' is missing the following properties from type 'Lift': constructs, lift ts(2322)
```
which is a way of saying "you are missing `constructs` and `lift` properties". These are required by the Lift type I just added.

In order to fix this, I must define these properties, however they can even be empty objects, which add nothing at all, like so:
```typescript
import type { AWS } from '@serverless/typescript';
import type { Lift } from 'serverless-lift';

const serverless: AWS & Lift = {
  service: 'my-serverless-service',
  frameworkVersion: '3',
  plugins: [
    'serverless-esbuild',
    'serverless-lift',
  ],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
  },
  constructs: {},
  lift: {},
};

module.exports = serverless;
```

I understand it may be reasonable to make `constructs` property required, as you must define it to actually make use of this plugin. However, I see no reason for `lift` property to be required, as it only holds the recently added `automaticPermissions` and I may very well leave it with the default value. Also, requiring the new `lift` property introduced an unnecessary **breaking change**, as everyone now needs to define this.

**Comment by afrittella** [comment]
Another workaround, if you don't want to put an empty object:
```typescript
const serverless: AWS & Partial<Lift> = {
      // ........
}
```

**Comment by mnapoli** [comment]
@GuiBeal this is a bug, feel free to send a pull request to make this property optional in the type.

**Comment by fredericbarthelet** [comment]
@mnapoli, I already was working on a fix + added the documentation on the missing `lift` property documentation. Thanks @GuiBeal for reporting this issue :)
