### ISSUE TITLE
Allow Use of AllViewer Managed Origin Request Policy

### ISSUE THREAD

**Issue by selfsimilar** [getlift/lift#229]
### Start from the Use-case

It is easy to bump up against the limit of ten white-listed headers to pass through CloudFront for `server-side-website` apps. However, AWS has a managed policy, [AllViewer](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html#managed-origin-request-policies-list), that passes through all headers, cookies, and query strings. I recently had an issue getting a Laravel site that uses Livewire to function properly, as neither project makes clear in their docs what headers they rely on for their security features.

### Example Config

```
constructs:
    website:
        # ...
        forwardedHeaders:
            - Accept
            - Accept-Language
            # ...
            - X-Custom-Header10
            - X-Custom-Header11 # Oops, too many! Assuming I even know what headers to whitelist.
```

### Implementation Idea

I suggest that the `server-side-website` configuration default to use of the `AllViewer` (id:216adef6-5c7f-47e4-b989-5492eafa07d3) managed origin request policy in the absence of the `forwardedHeaders` directive. If the `forwardedHeaders` directive is present, that will override the new default behavior and will create a new origin request policy the same as current behavior.

This change requires no changes to the configuration file, but it does have implicit behavior, which is not ideal.

As an alternative, we could add the following directive: `passAllHeadersToOrigin` with a default of `true`. The value of `true` will signal the use of the `AllViewer` managed origin request policy. A value of `false` will indicate the need for the `forwardedHeaders` directive.

I looked over the other four managed origin request policies, and none of them seemed useful or applicable to the `server-side-website` configuration, so as far as I can tell, the only meaningful options are managed (`AllViewer`) or custom.

I'm not familiar with Typescript, but on cursory examination, it shouldn't be a huge change to the code that actually generates the CloudFormation script. [Line 120 of ServerSideWebsite.ts](https://github.com/getlift/lift/blob/94387e6e1d004fe9360a47f947333f2ee80b3af6/src/constructs/aws/ServerSideWebsite.ts#L120) is where we'd put a check to determine managed or custom origin request policy.

It appears that we could instead say:
```ts
if (configuration.passAllHeadersToOrigin) {
    const backendOriginPolicy = OriginRequestPolicy.ALL_VIEWER;
}
else {
    // Current custom forwarded headers code.
}
```
based on my understanding of line [66 in origin-request-policy.ts](https://github.com/aws/aws-cdk/blob/74318c7d22bfc00de9e005f68a0a6aaa58c7db39/packages/%40aws-cdk/aws-cloudfront/lib/origin-request-policy.ts#L66).

Unless there are some security issues I'm not aware of, I think this would be the best way to turn CloudFront into a dumb pipe for the back-end server.

**Comment by selfsimilar** [comment]
After experimenting with this for a while it's clear that the `AllViewer` policy is not a solution as it results in 403: forbidden responses directly from the CF distribution. However, if you don't assign an origin request policy at all then **all** headers are passed back to the origin. The major stumbling block to this technique is that the response header `location` use the API Gateway domain name instead of the CloudFront domain. If I can set the API Gateway's custom domain name  to be the same as the CF distribution then this strategy may work and we can avoid needing to know about and whitelist every header we want to pass from CF to the app backend.

**Comment by mnapoli** [comment]
Ah yes, I think you pointed out why this won't work: we want to forward all headers except for the `Host` header.

Indeed, if we forward that header then API Gateway receives the wrong domain (not the API Gateway domain but the domain configured on CloudFront). Setting up the domain both on CF and API Gateway sounds really overkill.

But actually now that you mention it, that could be an option 🤷  After all the Lift construct has the possibility to automate everything, so… why not?

**Comment by esimonetti** [comment]
+1 from me @mnapoli  on passing more headers some way (removing the `Host`). It is easy to have to exceed 10 headers (eg: for CORS + other authentication/signature of integrations) and it got me in a bind now
