### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by kevincerro** [getlift/lift#234]
### Description

Since release 1.18.0 with the lift plugin on every `sls` command I get following exception:

Node version 12.22.10
NPM version 6.14.16

![Captura de Pantalla 2022-06-23 a las 12 49 18](https://user-images.githubusercontent.com/13980708/175282193-8a1ec9ce-829d-4166-a59d-057132c72c32.png)

![Captura de Pantalla 2022-06-23 a las 12 47 28](https://user-images.githubusercontent.com/13980708/175281881-a7b975d0-026c-47e9-9fd1-e746a5e65d11.png)

### How to Reproduce

1. Use Node version 12.22.10
2. Use NPM version 6.14.16
3. Install version 1.18.0 of lift plugin

### Additional Information

My plugins code in serverless file

```
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-lift
```

**Comment by wozniakm** [comment]
I'm having the same issue on version `1.17` and `1.19`.

**Comment by mnapoli** [comment]
Hi both, it seems you are using Node 12? Lift supports Node 14 and up as Node 12 is now deprecated.

https://github.com/getlift/lift/blob/3ebe40ddb48799ea8edbf4576ac33b82256e5a39/package.json#L58-L60

Could you try upgrading Node?
