### ISSUE TITLE
how to set RedrivePolicy

### ISSUE THREAD

**Issue by wutikorn-mat** [getlift/lift#257]
constructs:
  jobs:
    type: queue
    fifo: true
    batchSize: 5 # Lambda will receive 5 messages at a time
    delay: 60
    maxRetries: 3
    worker:
      handler: handler.consumer
      timeout: 10
    extensions:
      queue:
        Properties:
          QueueName: testQueue.fifo
          DelaySeconds: 0
          ReceiveMessageWaitTimeSeconds: 5
          MaximumMessageSize: 262144
          RedrivePolicy:
            deadLetterTargetArn: ${construct.jobs.dlqUrl}
            maxReceiveCount: 2
      dlq:
        Properties:
          QueueName: testQueue-DeadLetterQueue.fifo
          DelaySeconds: 0
          ReceiveMessageWaitTimeSeconds: 5
          MaximumMessageSize: 262144

**Comment by mnapoli** [comment]
Closing as I'm assuming it was an issue open by mistake.
