### ISSUE TITLE
Allow existing topic for DLQ Alarms

### ISSUE THREAD

**Issue by thejuan** [getlift/lift#277]
### Start from the Use-case

We have alerting infrastructure inplace that goes to more than just an email address, which we would like to re-use.

### Example Config

alarm: {topicArn} or ideally {topicName}

### Implementation Idea

If a topic is provided, use it rather than creating custom topics and email subs

**Comment by fredericbarthelet** [comment]
Hey @thejuan , #265 is now fixed.
I included an exemple of what you're trying to achieve in the form of a unit test.
https://github.com/getlift/lift/blob/5ff580efe8f126eb8a6fa57082b8229f2467c0cb/test/unit/queues.test.ts#L624-L646
This should allow you to specify your own SNS topic as destination for the alarm.

I'm closing this issue in the meantime, please feel free to reopen if you have additional questions.

Thanks
