### ISSUE TITLE
Node 20 is not supported

### ISSUE THREAD

**Issue by dnp1** [getlift/lift#335]
### Start from the Use-case

Trying to deploy my serverless using lift, but node 20 is not supported. 

Is a real incompatibility or just an unnecessary lock?

### Implementation Idea

Just update the engines array at package.json maybe will work?

**Comment by mnapoli** [comment]
Sounds good, you might also want to update the CI here: https://github.com/getlift/lift/blob/master/.github/workflows/ci.yml#L16-L19

**Comment by dnp1** [comment]
@mnapoli 
https://github.com/getlift/lift/pull/336

**Comment by mnapoli** [comment]
Thank you!
