### ISSUE TITLE
Define PriceClass for CloudFront distribution

### ISSUE THREAD

**Issue by jaulz** [getlift/lift#363]
### Start from the Use-case

It would be nice to define the price class for the Cloud Front distribution in order to save costs for unnecessary locations.

**Comment by mnapoli** [comment]
That could be achieved via extensions, I'm not sure we'll want to add an option for that given the low demand for this.

**Comment by jaulz** [comment]
@mnapoli thanks for your feedback. Actually, I thought the same but since the name of the CloudFront distribution is dynamic (i.e. appCDNXXXXXXX) I cannot modify it via extensions?

**Comment by mnapoli** [comment]
I meant something like this: https://github.com/getlift/lift#extend-lift-constructs Does that help?

**Comment by jaulz** [comment]
Ah, thanks a lot and sorry that I missed that piece! Will give it a try but I am confident that this will solve the issue 😊
