### ISSUE TITLE
Will there be serverless v4 compatibility?

### ISSUE THREAD

**Issue by cmcnicholas** [getlift/lift#393]
### Start from the Use-case

Serverless v4 is here. https://github.com/serverless/serverless/releases/tag/v4.0.26

**Comment by mnapoli** [comment]
Is that incompatible at the moment? Do you get any error?

**Comment by cmcnicholas** [comment]
> Is that incompatible at the moment? Do you get any error?

Just the version dependency currently.

    "serverless": "^3.28.0",

**Comment by mnapoli** [comment]
Understood, we can definitely relax that 👍 Before doing so, it would be great to get confirmation that it works fine :)

**Comment by austencollins** [comment]
FWIW our intention is to support the Lift plugin in Serverless Framework V.4, as always. We've done some testing recently and discovered a bug. We're working on a fix now and tracking it here: https://github.com/serverless/serverless/issues/12571

**Comment by rj-xy** [comment]
For anyone looking for a work-around for this, pinning serverless to the latest v3 gets around this issue for the moment, but not ideal.

**Comment by austencollins** [comment]
Lift should work seamlessly with V.4 now as of [this release](https://github.com/serverless/serverless/releases/tag/v4.0.35). We are continuing to test and monitor everything. Please let us know if you see further issues.

**Comment by dohomi** [comment]
I just started using lift with serverless and struggling with npm dependencies and layers. I use following v4 config:

```
build:
  esbuild:
    bundle: true
    minify: false
    target: node20
    packages: external
```

I bump into the issue that defined layers of construct fields of the yaml not work as expected, also the npm dependencies seem not to work out of the box.

**Comment by Vakintoshka** [comment]
hey guys, any updates on it? it's still impossible to npm install lift with serverless v4

**Comment by mnapoli** [comment]
https://github.com/serverless/serverless/issues/12571 still mentions issues, can anyone confirm whether Lift works with v4?

Also PRs are welcome.

**Comment by skierkowski** [comment]
@Vakintoshka Can you elaborate on the install issue you are seeing? If you are seeing the error with a serverless command, can you run `serverless support --github` and share the output.

**Comment by skierkowski** [comment]
@mnapoli Hi 👋 , long time! Yes, Serverless Framework v4 works with Lift. I'm confirming this based on analytics and testing. Having said that, there may still be some issues, like the one mentioned in the issue you linked, and the install issue @Vakintoshka mentioned. I'm trying to get the repro steps so we can fix them.

**Comment by mnapoli** [comment]
Hey @skierkowski! Thanks for the follow-up, I've merged a PR that allows installing lift with v4 👍
