### ISSUE TITLE
Function-specific commands should be simpler to use

### ISSUE THREAD

**Issue by mnapoli** [getlift/lift#56]
Here is an example with a queue construct:

```yaml
constructs:
    jobs:
        type: queue
        worker:
            ...
```

To view logs, I must type:

```
serverless logs -f <function-name>
```

**What's the function name?**

As a user, I need to know that Lift will generate a function named `jobsWorker`.

That should be simpler for users.

### Solution A

We could add construct commands, for example:

```
serverless jobs:worker:logs
serverless jobs:worker:deploy
...
```

The challenge is avoiding to reimplement commands and their options. I gave it a quick try:

- using `pluginManager.spawn()` wouldn't work here, as there doesn't seem to be a way to change the options for the spawned command (e.g. to pass the function name)
- spawning a subprocess could work (we would need to forward all the CLI options)

### Solution B

We could add an output to print the function name. That way users can find out what the function name is.

This approach requires more effort from the user, and is less discoverable. However it is more consistent with the existing commands.

**Comment by mnapoli** [comment]
Solution A was implemented for queues.

**Comment by ezmiller** [comment]
So if I have queue construct:
```
constructs:
  queue:
    type: queue
    worker:
      ...
```
Should this work: `sls queue:worker:deploy`? It doesn't for me. I get an error: `Cannot convert undefined or null to object`.

**Comment by raiseandfall** [comment]
Getting the same error here. Is this implemented?

**Comment by mnapoli** [comment]
@raiseandfall yes, could you open a separate issue with your Node version, Serverless version, and Lift version?

Thanks!
